# Setup
title:               Thamara Andrade
tagline:             'Thoughts of a Software Engineer that loves coffee and board games'
description:         'Thoughts of a Software Engineer that loves coffee and board games'
url:                 https://thamara.github.io/blog/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Thamara Andrade
  url:               https://twitter.com/thamyk
  email:             tkcandrade@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
